Repository lennycolton/vatglasses-data, pull requests merged in 2023-12, with the labels that each got.

#192 [ED] AIRAC changes 2312
  data/ed.json
Labels: merge-schedule-failed

#197 Nairobi North-South Splits Added
  data/hk.json
Labels: enhancement

#184 [2311] Italy 8.33kHz
  data/li.json
Labels: airac

#199 France 8.33kHz Transition
  data/lf.json
Labels: airac
