Repository lennycolton/vatglasses-data, pull requests merged in 2023-09, with the labels that each got.

#102 Add Bulgaria
  data/bulgaria.json
Labels: enhancement

#93 New Eurocontrol Positions
  data/adria.json
  data/bulgaria.json
  data/cyprus.json
  data/czechia.json
  data/euro.json
  data/france.json
  data/germany.json
  data/greece.json
  data/hungary.json
  data/moldova.json
  data/romania.json
  data/slovakia.json
Labels: airac

#101 8.33kHz UK
  data/uk.json
Labels: airac

#106 8.33kHz Germany
  data/germany.json
Labels: airac

#107 8.33kHz NL
  data/nl.json
Labels: airac

#110 Update greece.json
  data/greece.json
Labels: bug
